[env:lolin_s3_mini]
platform = espressif32
board = lolin_s3_mini
framework = arduino
monitor_speed = 2000000

; Configurações para o USB Nativo do S3 (importante para o Serial.print funcionar)
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    
    -D USER_SETUP_LOADED=1
    -D ST7789_DRIVER=1
    -D TFT_RGB_ORDER=TFT_BGR
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_INVERSION_OFF=1
    -D TFT_MISO=14
    -D TFT_MOSI=11
    -D TFT_SCLK=13
    -D TFT_CS=10
    -D TFT_DC=9
    -D TFT_RST=8
    -D TOUCH_CS=-1
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D SPI_FREQUENCY=20000000 ; 20MHz para o S3 aguentar os sprites
    -D SPI_READ_FREQUENCY=20000000
    -D SPI_TOUCH_FREQUENCY=2500000
    -D USE_HSPI_PORT=1

lib_deps =
    bodmer/TFT_eSPI @ ^2.5.0